# Generated by Django 4.0.5 on 2022-10-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=120, verbose_name='Файл картинки')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('body', models.TextField(verbose_name='Описание')),
                ('alt', models.TextField(verbose_name='Подсказка')),
                ('index', models.IntegerField(verbose_name='Индекс')),
            ],
            options={
                'db_table': 'certificates',
            },
        ),
    ]
