# Generated by Django 4.0.5 on 2022-10-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_сertificate_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='сertificate',
            name='alt',
            field=models.TextField(null=True, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='сertificate',
            name='body',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
