# Generated by Django 4.0.5 on 2022-10-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_project_description_alter_stack_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сertificate',
            old_name='body',
            new_name='sub_title',
        ),
    ]
